branch: development
description: Retrieve weather information from OpenWeatherMap
dockerhub: egeoffrey/egeoffrey-service-openweathermap
github: egeoffrey/egeoffrey-service-openweathermap
icon: cloud-sun
manifest_schema: 2
modules:
- service/openweathermap:
    description: Retrieve weather information from OpenWeatherMap
    module_configuration:
    - description: Your OpenWeatherMap API key
      format: string
      name: api_key
      required: true
    service_configuration:
      pull:
      - description: What to measure
        format: temperature|pressure|humidity|wind|wind_dir|condition|description|visibility|rain_1h|rain_3h|snow_1h|snow_3h|clouds|uv|forecast_temperature|forecast_pressure|forecast_humidity|forecast_wind|forecast_wind_dir|forecast_condition|forecast_description|forecast_visibility|forecast_rain_3h|forecast_snow_3h|forecast_clouds
        name: request
        required: true
      - description: The latitude of the location
        format: float
        name: latitude
        placeholder: 12.33
        required: true
      - description: The longitude of the location
        format: float
        name: longitude
        placeholder: 70.11
        required: true
package: egeoffrey-service-openweathermap
revision: 19
tags: service weather
version: 1.0
